version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
     - ${ENV_CONTAINER_PATH}/global.env
     #- ${ENV_CONTAINER_PATH}/evett.global.env
    environment:
      - DATABASE_URL=sqlite:///%kernel.project_dir%/var/data.db
      - LOCALE=en
      - APP_ENV=dev
    volumes:
      - .:/srv/symfony:rw
    networks:
      - private
#  db:
#    build:
#      context: ./docker/db
#      dockerfile: ./Dockerfile
#    expose:
#      - 3306
#    environment:
#      - MYSQL_ROOT_PASSWORD=symfony
#      - MYSQL_DATABASE=symfony
#      - MYSQL_PASSWORD=symfony
#      - MYSQL_USER=symfony
#    volumes:
#      - db-data:/var/lib/mysql:rw
#      # for sql dumps
#      - ./sql-dumps:/var/sql-dumps:rw
  web:
    build:
      context: ./docker/nginx
      dockerfile: ./Dockerfile
    expose:
        - 80
    networks:
      - reverse-proxy
      - private
      - shared
    environment:
      - VIRTUAL_HOST=evett-staging.${HOSTNAME}
      - LETSENCRYPT_HOST=evett-staging.${HOSTNAME}
      - LETSENCRYPT_EMAIL=${EMAIL}
    volumes:
      # Comment out the next line in production
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./public:/srv/symfony/public:ro

#volumes:
#  db-data: {}

networks:
  reverse-proxy:
    external:
      name: reverseproxy_default
  shared:
    external:
      name: shared
  private:
    driver: bridge
