version: '3'

services:
  app:
    image: malulu/php-7.1:latest
    env_file:
     - ${ENV_CONTAINER_PATH}/global.env
     - ${ENV_CONTAINER_PATH}/evett.global.env
    environment:
      - DATABASE_URL=mysql://root:${DB_PW}@servus_db_1:3306/evett
      - LOCALE=en
      - APP_ENV=dev
    volumes:
      - .:/srv/symfony:rw
    networks:
      - private
      - shared
  web:
    build:
      context: ./docker/nginx
      dockerfile: ./Dockerfile
    expose:
        - 80
    networks:
      - reverse-proxy
      - private
      - shared
    environment:
      - VIRTUAL_HOST=evett-staging.${HOSTNAME}
      - LETSENCRYPT_HOST=evett-staging.${HOSTNAME}
      - LETSENCRYPT_EMAIL=${EMAIL_ADMIN}
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./public:/srv/symfony/public:ro

networks:
  reverse-proxy:
    external:
      name: reverseproxy_default
  shared:
    external:
      name: shared
  private:
    driver: bridge
